version: "3"

services:
  application:
    container_name: api-nois-invest
    build:
      context: .
      dockerfile: Dockerfile.dev
    user: root
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    env_file:
      - docker/api/docker.env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - database
    networks:
      - nesjs-network

  database:
    container_name: database-nois-invest
    build:
      context: docker/postgresql
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - ${POSTGRESQL_PORT}:${POSTGRESQL_PORT}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - nesjs-network

networks:
  nesjs-network:
    driver: bridge
